name: Docker Image CI - Build Check on Main

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image - frontend
      run: docker build "frontend" --tag docker.happyfir.com/misc/soen390:latest
    - name: Build the Docker image - user-service
      run: docker build "user-service" --tag docker.happyfir.com/misc/soen390-userservice:latest
    - name: Build the Docker image - server
      run: docker build "server" --tag docker.happyfir.com/misc/soen390-server:latest