name: Docker Image CI - Build Check on Main

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image - frontend
      run: docker build "frontend" --tag docker.happyfir.com/misc/soen390:latest
    - name: Build the Docker image - backend
      run: docker build "backend" --tag docker.happyfir.com/misc/soen390-backend:latest